spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: passw0rd
logging:
  level:
    org.springframework.data: INFO
    org.neo4j: DEBUG
    ch.qos.logback: INFO
